CC = gcc

solution: reverseLinkedList.c
	$(CC) reverseLinkedList.c -o reverseLinkedList -Wall -Wextra -Wno-unused-variable -Wconversion -Wshadow -Wcast-qual -fstack-protector-strong -pedantic -std=c99 -g -lm -fsanitize=address,undefined
